version: '3'

volumes:
  postgres_data_licenta:
      driver: local
  pgadmin-data:
      driver: local
      
networks:
  local:
    name: local
    driver: bridge

services:
  postgreslicenta:
      image: postgres:16.4
      volumes:
        - postgres_data_licenta:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: admin
      ports:
       - 5433:5432
      networks:
       - local
  pgadminlicenta:
    container_name: pgadminlicenta
    image: "dpage/pgadmin4:latest"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - local
  keycloaklicenta:
      image: quay.io/keycloak/keycloak:latest
      command: start-dev
      environment:
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://postgreslicenta/keycloaklicenta
        KC_DB_USERNAME: postgres
        KC_DB_PASSWORD: admin
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      ports:
        - 8082:8080
      depends_on:
        - postgreslicenta
      networks:
        - local
